version: 2.1

executors:
  node-maintenance:
    docker:
      - image: circleci/node:14-stretch
    environment:
      - MB_SLOW_TEST_TIMEOUT: 10000
  node-active:
    docker:
      - image: cimg/node:lts
    environment:
      - MB_SLOW_TEST_TIMEOUT: 10000
  node-current:
    docker:
      - image: cimg/node:current
    environment:
      - MB_SLOW_TEST_TIMEOUT: 10000

jobs:
  build:
    executor: node-active
    environment:
      - CC_TEST_REPORTER_ID=8bc3a050a2f8ef1cc460e5f4c72d18a689c8ae0981bf494031eb4eb28bbd0b0b
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install mountebank
            npm ci
      - store_test_results:
          path: testResults

  unit:
    executor: node-active
    steps:
      - checkout
      - run:
          name: Pull Mountebank
          command: git clone git@github.com:bbyars/mountebank.git ../mountebank
      - run: npm run test:unit
      - run:
          name: Web tests
          command: npm run test:web

  performance:
    executor: node-active
    environment:
      - MB_PORT: 3535
      - MB_EXECUTABLE: /home/circleci/project/node_modules/.bin/mb
    steps:
      - checkout
      - run:
          name: Pull Mountebank
          command: git clone git@github.com:bbyars/mountebank.git ../mountebank
      - run:
          name: Test
          command: npm run test:perf
      - store_test_results:
          path: dist/test/testResults

  web:
    executor: node-active
    environment:
      - MB_PORT: 3535
      - MB_EXECUTABLE: /home/circleci/project/node_modules/.bin/mb
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            node tasks/mb.js start --allowInjection --localOnly
            (npm run test:web)
      - store_test_results:
          path: dist/test/testResults

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - unit:
          requires:
            - build
          filters:
            branches:
              only: master
      - performance:
          requires:
            - build
          filters:
            branches:
              only: master
      - web:
          requires:
            - build
          filters:
            branches:
              only: master
