version: 2.1

executors:
  node-maintenance:
    docker:
      - image: circleci/node:14-stretch
    environment:
      - MB_SLOW_TEST_TIMEOUT: 10000
  node-active:
    docker:
      - image: cimg/node:lts
    environment:
      - MB_SLOW_TEST_TIMEOUT: 10000
  node-current:
    docker:
      - image: cimg/node:current
    environment:
      - MB_SLOW_TEST_TIMEOUT: 10000

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: node-active
    environment:
      - CC_TEST_REPORTER_ID=8bc3a050a2f8ef1cc460e5f4c72d18a689c8ae0981bf494031eb4eb28bbd0b0b
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install mountebank
            npm ci
      - store_test_results:
          path: testResults
      - persist_to_workspace:
          root: .
          paths:
            - tasks
            - scripts
            - Procfile

  windows:
    executor: win/default
    environment:
      - MB_SLOW_TEST_TIMEOUT: 10000
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install mountebank
            npm ci
      - run:
          name: Test
          command: |
            npm run test:cover
            npm run test:api
            npm run test:cli
      - store_test_results:
          path: testResults

  mac:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: install node
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo nvm install 14 >> $BASH_ENV
            echo nvm alias default 14 >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: |
            npm install mountebank
            npm ci
      - run:
          name: Test
          command: |
            npm run test:cover
            npm run test:api
            npm run test:cli
      - store_test_results:
          path: testResults

  maintenanceOutOfProcessImposters:
    executor: node-maintenance
    environment:
      - MB_PORT: 3535
      - MB_PERSISTENT: true
      - MB_EXECUTABLE: /home/circleci/project/dist/mountebank/bin/mb
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Prepare to run out of process protocol implementations
          command: node tasks/createProtocolsFile.js outOfProcess.json
      - run:
          name: Test
          command: |
            node tasks/mb.js start --allowInjection ---localOnly --protofile outOfProcess.json
            (cd dist/test && npm test)
      - store_test_results:
          path: dist/test/testResults

  performance:
    executor: node-active
    environment:
      - MB_PORT: 3535
      - MB_EXECUTABLE: /home/circleci/project/dist/mountebank/bin/mb
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: cd dist/test && npm run perf
      - store_test_results:
          path: dist/test/testResults

  web:
    executor: node-active
    environment:
      - MB_PORT: 3535
      - MB_EXECUTABLE: /home/circleci/project/dist/mountebank/bin/mb
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            node tasks/mb.js start --allowInjection --localOnly
            (cd dist/test && npm run web)
      - store_test_results:
          path: dist/test/testResults

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - windows:
          filters:
            branches:
              only: master
      - mac:
          filters:
            branches:
              only: master
      - performance:
          requires:
            - build
          filters:
            branches:
              only: master
      - web:
          requires:
            - build
          filters:
            branches:
              only: master
